### ISSUE TITLE
Add option to return home instead of pause when switching off the cleaning button

### ISSUE THREAD

**Issue by Tomcraft1980** [thoukydides/homebridge-aeg-robot#52]
### Description of Enhancement

You currently promote two buttons to HomeKit, one for "cleaning" (play/pause) and one for "return home" (home/pause).
It would be useful to have a single button for this like:
Turn on: play
Turn off: home

### AEG/Electrolux Appliance(s)

AEG RX9-2-4ANM 900 277 479

**Comment by thoukydides** [comment]
Apple are supposed to be adding native robot vacuum cleaner support to HomeKit imminently, so I would prefer to wait for that and integrate it properly rather than making this sort of change now.

Even if appropriate characteristics/services weren't going to be added I would not be keen on this approach:
1. It would not be good for indicating the clean being paused. If the switch is set to off then it would not be possible to initiate a return home. If the switch is set on then it would not be possible to resume the clean.
2. My own use is more often to pause the clean (when the doorbell or phone rings) than to return home.
3. I am generally not keep on implementing multiple alternate interfaces to the same functionality.

I might reconsider this after seeing what Apple end up defining, but for now I do not intend to implement this suggestion.

**Comment by Tomcraft1980** [comment]
My usage is a little other from yours.
I never use the pause function for the robots as I set up an automation that triggers all vacuums, when nobody is at home (last person left home) and sends them back to the dock, when the first person arrives back at home.

If someone wants to implement this like me, simply edit the following file via HB console using the following commad, although it might be a little frustrating to edit this file again after every plugin update:
`nano node_modules/homebridge-aeg-robot/dist/accessory-robot.js`

Search in _addSwitchClean() {...}_
```javascript
            const command = value ? 'play' : 'pause';`
``` 
And replace with:

```javascript
            //const command = value ? 'play' : 'pause';
            const command = value ? 'play' : 'home';
```
