### ISSUE TITLE
Plugin not workling anymore? API changes?

### ISSUE THREAD

**Issue by Tomcraft1980** [thoukydides/homebridge-aeg-robot#58]
### Description of Issue

The plugin stopped working for me since november 10.
Did AEG changes to the API again?
Is it working for you @thoukydides?

### Plugin Version

2.2.4 

### AEG/Electrolux Appliance(s)

AEG RX9-1-IBM 900 277 268, AEG RX9-2-4-ANM 900 277 479, AEG RX9-2-6-IBM 900 277 480

### Diagnostic Checks

- [X] AEG iPhone app is able to control the appliance.

**Comment by thoukydides** [comment]
There appears to have been some server-side issues on 11th and 12th November, which required me to generate new Access and Refresh Tokens. However, since then it has been working fine for me.

What issues are you seeing?

**Comment by Tomcraft1980** [comment]
Ah good hint!
I had to generate a new API key as well as Access and Refresh Tokens.
Now it works again, thanks!

**Comment by thoukydides** [comment]
It looks like the authentication servers had some problems. I am using two access/refresh token pairs with the same API key - one for my production Homebridge setup, and one for testing this plugin. The token refresh for the production setup appears to have returned invalid tokens requiring new ones to be issued manually. The test token pair was refreshed successfully and remain valid.

The API documentation does mention that "there is an upper limit on the amount of token pairs a user can have at the same time" but without any explanation of what happens when the limit is reached... and unlike almost every other OAuth implementation the dashboard does not list the currently issued tokens or allow their revocation. Perhaps you hit that limit and generating a new API Key would have started afresh. Or maybe the authentication servers just screwed up worse.

Many other OAuth implementations keep the same refresh token and only rotate the access token. That approach avoids this problem since when things recover a new token refresh will automatically yield a good access token. But with that approach the Dashboard would need to provide a revocation mechanism in case the refresh tokens leak.

**Comment by Tomcraft1980** [comment]
Thanks for the explanation.
I am glad it works again. ;-)

**Comment by Tomcraft1980** [comment]
Is it necessary again to get a new API code?
```shell
[03/12/2024, 05:03:33] [Homebridge AEG Robot Vacuum] [AEG RX9-1-IBM] Lost connection to cloud servers: Appliance state watchdog timeout
```

**Comment by Tomcraft1980** [comment]
You are right, they are back up. ;-)
